import { Talent } from '../../Classes'

export default [
  new Talent(
    'Reflection',
    'reflection',
    ['Allows ', '% of your Mana regeneration to continue while casting.'],
    3,
    [[10, 20, 30]],
    null,
    null,
    null,
    null,
    null,
    null,
    ['D2']
  ),
  new Talent('Sublety', 'sublety', ['Reduces the threat generated by your spells by ', '%.'], 3, [[7, 14, 20]]),
  new Talent(
    'Insect Swarm',
    'insect-swarm',
    ['The enemy target is swarmed by insects, decreasing their chance to hit by 2% and causing 66 Nature damage over 12 sec.'],
    1,
    [[1]],
    [{ x: null, y: null }],
    [{ x: 4, y: 2 }],
    '45 Mana',
    '30 yd range',
    'Instant',
    null,
    ['D2']
  ),
  null,
]
