import { Talent } from '../../Classes'

export default [
  new Talent(
    'Improved Charge',
    'ability_warrior_charge',
    ['Increases the rage generated by your charge by ', ' and increases its range by ', ' yards.'],
    2,
    [
      [3, 6],
      [3, 6],
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: false,
      isChanged: true,
      isMoved: false,
    }
  ),
  new Talent(
    'Tactical Mastery',
    'spell_nature_enchantarmor',
    ['You retain up to an additional', ' rage points when you change stances.'],
    3,
    [[5, 10, 15]],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: false,
      isChanged: true,
      isMoved: false,
    }
  ),
  null,
  new Talent(
    'Improved Thunder Clap',
    'ability_thunderclap',
    ['Reduces the rage cost of your thunder clap by ', ' and increases its damage by ', '% when hitting a single target.'],
    3,
    [
      [1, 2, 3],
      [100, 200, 300],
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: false,
      isChanged: true,
      isMoved: false,
    }
  ),
]
