import { Talent } from '../../Classes'

export default [
  new Talent('Improved Charge', 'entangling-roots', ['Increases the amount of Rage generated by your charge by ', '.'], 2, [[3, 6]]),
  new Talent('Tactical Mastery', 'moonfire', ['You retain up to ', ' rage points when you change stances.'], 5, [[5, 10, 15, 20, 25]]),
  null,
  new Talent(
    'Improved Thunder Clap',
    'arcane-explosion',
    ['Reduces the rage cost of your thunder clap by ', ' and increases its damage by ', '% when hitting a single target.'],
    3,
    [
      [1, 2, 3],
      [100, 200, 300],
    ]
  ),
]
