import { Talent } from '../../Classes'

export default [
  new Talent("Nature's Grace", 'healing-touch', ['Reduces the threat generated by your Healing spells by ', '%.'], 3, [[5, 10, 15]]),
  new Talent(
    'Healing Focus',
    'healing-focus',
    ['Gives you a ', '% chance to avoid interruption caused by damage while casting any healing spell.'],
    5,
    [[14, 28, 42, 56, 70]]
  ),
  new Talent('Totemic Mastery', 'totemic-mastery', ['Increases the range of your totems that affect friendly targets to 30 yards.'], 1, [[]]),
  null,
]
