import { Talent } from '../../Classes'

<<<<<<< HEAD
const tier3 = [
  new Talent("Nature's Guidance", 'spell_frost_stun', ['Increases your chance to hit with melee attacks and spells by ', '%.'], 3, [[1, 2, 3]]),
  new Talent('Healing Focus', 'spell_nature_healingwavelesser', ['Gives you a ', '% chance to avoid interruption caused by damage while casting any healing spell.'], 5, [[14, 28, 42, 56, 70]]),
  new Talent('Totemic Mastery', 'spell_nature_nullward', ['Increases the radius of your totems that affect friendly targets to 30 yards.'], 1, [[]]),
  new Talent(
    "Nature's Grace",
    'spell_nature_healingtouch',
    ['Reduces the threat generated by your Healing and Lightning spells by ', '%.'],
    3,
    [[7, 14, 20]],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: false,
      isChanged: true,
      isMoved: false,
    }
  ),
=======
export default [
	new Talent(
		"Nature's Grace",
		'spell_nature_healingtouch',
		['Reduces the threat generated by your Healing spells by ', '%.'],
		3,
		[[5, 10, 15]]
	),
	new Talent(
		'Healing Focus',
		'spell_nature_healingwavelesser',
		['Gives you a ', '% chance to avoid interruption caused by damage while casting any healing spell.'],
		3,
		[[23, 47, 70]],
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{
			isNew: false,
			isChanged: true,
			isMoved: false,
		}
	),
	new Talent(
		'Totemic Mastery',
		'spell_nature_nullward',
		['Increases the radius of your totems that affect friendly targets to 30 yards and increases their effect by 5%.'],
		1,
		[[]],
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{
			isNew: false,
			isChanged: true,
			isMoved: false,
		}
	),
	null,
>>>>>>> 1ddb4f1 (patch notes)
]

export default tier3
