import { Talent } from '../../Classes'

const tier2 = [
  new Talent(
    'Improved Bloodrage',
    'ability_racial_bloodrage',
    ['Increases the instant Rage generated by your Bloodrage ability by ', '.'],
    2,
    [[2, 5]],
    [{ x: null, y: null }],
    [{ x: 2, y: 0 }],
    null,
    null,
    null,
    null,
    ['D1']
  ),
  null,
  new Talent(
    'Toughness',
    'spell_holy_devotion',
    ['Increases your armor value from items by ', '% and reduces the duration of movement slowing effects on you by ', '%.'],
    5,
    [
      [2, 4, 6, 8, 10],
      [10, 20, 30, 40, 50],
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: false,
      isChanged: true,
      isMoved: false,
    }
  ),
  new Talent(
    'Rushing Victories',
    'ability_warrior_devastate',
    ['Gain ', ' rage points and ', '% health after killing an opponent that yields experience or honor.'],
    2,
    [
      [5, 10],
      [5, 10],
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: true,
      isChanged: false,
      isMoved: false,
    }
  ),
]

export default tier2
