import { Talent } from '../../Classes'

export default [
  new Talent(
    'Improved Bloodrage',
    'healing-touch',
    ['Increases the instant Rage generated by your Bloodrage ability by ', '.'],
    2,
    [[2, 5]],
    [{ x: null, y: null }],
    [{ x: 2, y: 0 }],
    null,
    null,
    null,
    null,
    ['D1']
  ),
  null,
  new Talent(
    'Toughness',
    'chain-heal',
    ['Increases your armor value from items by ', '% and reduces the duration of movement slowing effects on you by ', '%.'],
    5,
    [
      [2, 4, 6, 8, 10],
      [10, 20, 30, 40, 50],
    ]
  ),
  new Talent('Anticipation', 'enrage', ['Increases your defense skill by ', '.'], 3, [[4, 7, 10]]),
]
