import { Talent } from '../../Classes'

const tier4 = [
  new Talent(
    'Arctic Reach',
    'spell_shadow_darkritual',
    ['Increases the range of your Frostbolt and Blizzard spells and the radius of your Frost Nova and Cone of Cold spells by ', '%.'],
    2,
    [[10, 20]]
  ),
  new Talent(
    'Frost Channeling',
    'spell_frost_stun',
    ['Reduces the mana cost of your Frost Spells by ', '% and reduces the threat generated by your Frost spells by ', '%.'],
    3,
    [
      [5, 10, 15],
      [10, 20, 30],
    ]
  ),
  new Talent(
    'Fingers of Frost',
    'spell_frost_manarecharge',
    [
      'Gives your Frostbolt a ',
      '% chance to grant you the Ice Flows effect, which treats your next two spells cast as if the target were frozen. Lasts 15 sec.',
    ],
    2,
    [[10, 20]],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { isNew: true, isChanged: false, isMoved: false }
  ),
  null,
]

export default tier4
