import { Talent } from '../../Classes'

const tier4 = [
  new Talent('Arctic Reach', 'spell_shadow_darkritual', ['Increases the range of your Frostbolt and Blizzard spells and the radius of your Frost Nova and Cone of Cold spells by ', '%.'], 2, [[10, 20]]),
  new Talent('Frost Channeling', 'spell_frost_stun', ['Reduces the mana cost of your Frost Spells by ', '% and reduces the threat generated by your Frost spells by ', '%.'], 3, [
    [5, 10, 15],
    [10, 20, 30],
  ]),
  new Talent(
    'Elemental Volatility',
    'ability_dualwieldspecialization',
    ['Critical strikes from your Frost spells increase the damage of your Fire spells by ', '% for 8 sec. Critical strikes from your Fire spells increase the damage of your Frost spells by ', '% for 8 sec.'],
    2,
    [
      [10, 20],
      [10, 20],
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { isNew: true, isChanged: false, isMoved: false }
  ),
  null,
]

export default tier4
